# Use root/example as user/password credentials
version: '3.7'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080
    deploy:
      replicas: 1
    networks:
      - default
networks:
  default:
    external:
      name: dev_overlay
