# Use root/example as user/password credentials
version: '3.7'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.name == hp]
    networks:
      - default
    environment:
      ADMINER_PLUGINS: 'tables-filter dump-date dump-json dump-zip json-column sql-log'
      ADMINER_DEFAULT_SERVER: 10.144.106.92
networks:
  default:
    external:
      name: dev_overlay
