# Use root/example as user/password credentials
version: '3.7'

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.0.2
    restart: always
    volumes:
      - xxl-job_applogs:/data/applogs
    environment:
      - PARAMS= --spring.datasource.url=jdbc:mysql://aliyun.kikera.top:4406/xxl-job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=root
    ports:
      - 8086:8080
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.host == tencent
    networks:
      - default
volumes:
  xxl-job_applogs:
networks:
  default:
    external:
      name: dev_overlay
