version: '3.7'
services:
  lanproxy-client-us:
    image: harvies/lanproxy-client
    environment:
      # 这里是在lanproxy后台配置的密钥
      - LANPROXY_KEY=391cfde42fdc4830a033925e889bf772
      # 服务器的ip，支持域名
      - LANPROXY_HOST=us.kikera.top
    restart: always
    network_mode: host
