version: '3'
services:
  lanproxy-server:
    image: harvies/lanproxy-server
    container_name: lanproxy-server
    environment:
      # 配置你的账号
      - LANPROXY_USERNAME=admin
      # 配置你的密码
      - LANPROXY_PASSWORD=Lisi@123
    restart: always
    network_mode: host
