version: "3.7"

services:
  spring-boot-admin:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-spring-boot-admin-server:latest
    networks:
      - default
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10m
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 500M
          cpus: '2'
    environment:
      charon.env: dev
      spring.cloud.inetutils.preferred-networks: 10.0.3
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: charon-spring-boot-admin-server
networks:
  default:
    external:
      name: dev_overlay
