version: "3.7"

services:
  charon-spring-boot-admin-server:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-spring-boot-admin-server:latest
    networks:
      - default
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
          cpus: '8'
    environment:
      env: dev
      spring.cloud.inetutils.preferred-networks: 10.0.3
      #spring.cloud.inetutils.ignoredInterfaces[0]: eth1
      #spring.cloud.inetutils.ignoredInterfaces[1]: eth2
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: charon-spring-boot-admin-server
networks:
  default:
    external:
      name: dev_overlay
