version: "3"

services:
  blazars:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-spring-boot-admin-server:latest
    networks:
      - default
    ports:
      - "8082:8080"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 400M
          cpus: '2'
    environment:
      env: dev
networks:
  default:
    external:
      name: dev_overlay
