version: '3.7'
services:
  rmqnamesrv:
    image: foxiswho/rocketmq:server-4.6.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/rocketmq/server/logs:/opt/logs
      - ./data/rocketmq/server/store:/opt/store
    networks:
      rmq:
        aliases:
          - rmqnamesrv

  rmqbroker:
    image: foxiswho/rocketmq:broker-4.6.1
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./data/rocketmq/broker/logs:/opt/logs
      - ./data/rocketmq/broker/store:/opt/store
      - ./data/rocketmq/broker/config/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker

  rmqconsole:
    image: pongsky/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8089:8080
    environment:
      JAVA_OPTS: "-Drocketmq.config.namesrvAddr=rmqnamesrv:9876"
    volumes:
      - ./data/rocketmq/console/data/users.properties:/tmp/rocketmq-console/data/users.properties
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole
networks:
  rmq:
    name: rmq
    driver: bridge