version: "3"

services:
  dubbo-proxy:
    image: harvies/dubbo-proxy:latest
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
    ports:
      - 7000:8000
    environment:
      proxy.registry.address: zookeeper://server1:2181,server2:2182,server3:2183
      proxy.registry.group: dubbo
      proxy.metadata-report.address: zookeeper://server1:2181,server2:2182,server3:2183
networks:
  default:
    external:
      name: dev_overlay
