version: '3.7'

services:
  dubbo-admin:
    image: harvies/dubbo-admin
    restart: always
    hostname: dubbo-admin
    ports:
      - 2179:8080
    environment:
      - admin.registry.address=zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
      - admin.config-center=zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
      - admin.metadata-report.address=zookeeper://zoo1:2181,zoo2:2181,zoo3:2181
      - admin.root.user.name=root
      - admin.root.user.password=root
    networks:
      - default
networks:
  default:
    external: true
    name: dev_overlay